import axios from 'axios';
import API_BASE_URL from '../config/api.config.js';

const ORDERS_URL = `${API_BASE_URL}/admin/orders`;

// Get all orders for admin
export const getAllOrders = async () => {
	try {
		const token = localStorage.getItem('access');
		if (!token) {
			throw new Error('No access token found. Please login first.');
		}
		
		const response = await axios.get(ORDERS_URL, {
			headers: {
				'Content-Type': 'application/json',
				'Authorization': `Bearer ${token}`
			}
		});
		
		// Backend returns: [{ OrderId, OrderDate, Status, TotalPrice, PublisherId, Username, IsAutoGenerated, ConfirmedBy, Items: [{ ISBN, Quantity, UnitPrice }] }]
		// Handle both PascalCase and camelCase, and DateOnly serialization
		return Array.isArray(response.data) ? response.data.map(order => {
			const orderDate = order.OrderDate || order.orderDate;
			// Handle DateOnly serialization (could be string "YYYY-MM-DD" or Date object)
			let dateValue = null;
			if (orderDate) {
				if (typeof orderDate === 'string') {
					dateValue = orderDate;
				} else if (orderDate instanceof Date) {
					dateValue = orderDate.toISOString().split('T')[0];
				} else {
					dateValue = String(orderDate);
				}
			}

			// Process order items
			const items = Array.isArray(order.Items || order.items) ? (order.Items || order.items).map(item => ({
				isbn: item.ISBN || item.isbn || '',
				quantity: parseInt(item.Quantity || item.quantity || 0),
				unitPrice: parseFloat(item.UnitPrice || item.unitPrice || 0)
			})) : [];

			return {
				orderId: order.OrderId || order.orderId,
				orderDate: dateValue,
				status: (order.Status || order.status || '').toString(),
				totalPrice: parseFloat(order.TotalPrice || order.totalPrice || 0),
				publisherId: parseInt(order.PublisherId || order.publisherId || 0),
				confirmedBy: order.ConfirmedBy || order.confirmedBy || null,
				items: items
			};
		}) : [];
	} catch (error) {
		console.error('Error fetching orders:', error.response?.data);
		throw error;
	}
};

// Confirm an order (add quantity to stock)
export const confirmOrder = async (orderId) => {
	try {
		const token = localStorage.getItem('access');
		// Backend expects: { Status: string }
		const response = await axios.put(
			`${ORDERS_URL}/${orderId}/status`,
			{ Status: 'Confirmed' },
			{
				headers: {
					'Content-Type': 'application/json',
					'Authorization': `Bearer ${token}`
				}
			}
		);
		return response.data;
	} catch (error) {
		console.error('Error confirming order:', error.response?.data);
		throw error;
	}
};

// Cancel an order
export const cancelOrder = async (orderId) => {
	try {
		const token = localStorage.getItem('access');
		// Backend expects: { Status: string }
		const response = await axios.put(
			`${ORDERS_URL}/${orderId}/status`,
			{ Status: 'Canceled' },
			{
				headers: {
					'Content-Type': 'application/json',
					'Authorization': `Bearer ${token}`
				}
			}
		);
		return response.data;
	} catch (error) {
		console.error('Error canceling order:', error.response?.data);
		throw error;
	}
};


// Get pending orders only
export const getPendingOrders = async () => {
	try {
		const token = localStorage.getItem('access');
		const response = await axios.get(ORDERS_URL, {
			params: { status: 'Pending' },
			headers: {
				'Content-Type': 'application/json',
				'Authorization': `Bearer ${token}`
			}
		});
		return response.data;
	} catch (error) {
		console.error('Error fetching pending orders:', error.response?.data);
		throw error;
	}
};
